// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ad_7PjR04ChHysjwlQw7O5Hnor4yJUs',
    appId: '1:10391525378:web:76cdc65725aa9da25d2f1b',
    messagingSenderId: '10391525378',
    projectId: 'staff-ease',
    authDomain: 'staff-ease.firebaseapp.com',
    storageBucket: 'staff-ease.firebasestorage.app',
    measurementId: 'G-HL69VTW3YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDqQqLXg5nYE3kNM5Bn-yyD8rZMWUGms',
    appId: '1:10391525378:android:ab93978b383170685d2f1b',
    messagingSenderId: '10391525378',
    projectId: 'staff-ease',
    storageBucket: 'staff-ease.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6t5j2xMJNnqz8uQZ62v3bYUeSmqX1tjo',
    appId: '1:10391525378:ios:8cfa86c28755b42d5d2f1b',
    messagingSenderId: '10391525378',
    projectId: 'staff-ease',
    storageBucket: 'staff-ease.firebasestorage.app',
    iosBundleId: 'com.example.staffEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6t5j2xMJNnqz8uQZ62v3bYUeSmqX1tjo',
    appId: '1:10391525378:ios:8cfa86c28755b42d5d2f1b',
    messagingSenderId: '10391525378',
    projectId: 'staff-ease',
    storageBucket: 'staff-ease.firebasestorage.app',
    iosBundleId: 'com.example.staffEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3ad_7PjR04ChHysjwlQw7O5Hnor4yJUs',
    appId: '1:10391525378:web:f052f4fd7481f05e5d2f1b',
    messagingSenderId: '10391525378',
    projectId: 'staff-ease',
    authDomain: 'staff-ease.firebaseapp.com',
    storageBucket: 'staff-ease.firebasestorage.app',
    measurementId: 'G-BKN4XPMSS8',
  );
}
